#!/bin/bash

# Now upload all data to database and wunderground
while true; do 
	ssh -Ng -L 3306:127.0.0.1:3306 hjvveluw@s14.servitnow.nl &
        echo 'Opened SSH tunnel [OK]'
	PID=$!
        sleep 1
        echo mlu | sudo python agent.py
        echo mlu | sudo kill -9 $PID
        echo 'Closed SSH tunnel [OK]'
        sleep 300
done

